title: Copperblog
email: ben@factual.com
description: >
  A hip, new static site for weird posts about interesting data. Maybe
  even some pictures of cats.
baseurl: ""
url: bcoppersmith.github.io
twitter_username: bencoppersmith
github_username:  bcoppersmith
include: ["_pages"]
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed
